  name: Despliegue continuo a QA
  on:
    push:
      branches:
        - 'hotfix/*'
        - 'release/*'
  jobs:
    setup-build:
      name: Configurar, Construir
      runs-on: ubuntu-latest
      env:
        PROJECT_ID: ${{ secrets.CGP_PROJECT }}
        KEY: ${{ secrets.GCP_KEY }}
        API_ZONE: ${{ secrets.GCP_ZONE_QA }}
        API_CLUSTER: ${{ secrets.GCP_CLUSTER_QA }}
        API_KEY: ${{ secrets.API_KEY_QA }}
        MONGO_IP: ${{ secrets.MONGO_IP_QA }}
        URL: ${{ secrets.API_URL_QA }}
        ONE_SIGNAL_APP_ID: ${{ secrets.ONE_SIGNAL_APP_ID_QA }}
        ONE_SIGNAL_TOKEN: ${{ secrets.ONE_SIGNAL_TOKEN_QA }}
        ONE_SIGNAL_URL: ${{ secrets.ONE_SIGNAL_URL_QA }}
        NODE_ENV: "dev"
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Build Test
          env:
            #Variables usadas solo para la ejecución de las pruebas
            MONGO_URI: "mongodb://localhost:27017/hrapp_dev"
            PORT: "3000"
            HOST_NAME: "localhost"
            JWT_SECRET: "TEST"
          run: |
            chmod +x ./gradlew
            ./gradlew helmInstallToCloud